before_script:
  - bundle install
  - rake db:create
  - rake db:migrate RAILS_ENV=test

test_reporting:
  script:
    - chmod 755 script/generate_test_reporting.sh
    - ./script/generate_test_reporting.sh
